### ISSUE TITLE
Allow standalone extension of Bionty with custom terms

### ISSUE THREAD

**Issue by Zethson** [laminlabs/bionty-base#222]
We should allow standalone users to quickly plug in their own terms by adding lines to the DF.

The API could be something like:

`bt.extend_ontology(new_terms: pd.DataFrame)`

which appends the DataFrame to the Entity DataFrame.

**Comment by sunnyosun** [comment]
I think an easy way that's following the current design could be:

Simply providing the link to the dataframe instead of the url here:
```
Disease:
  doid:
    versions:
      2023-01-30: http://purl.obolibrary.org/obo/doid/releases/2023-01-30/doid.obo
  inhouse-vocab:
    versions:
      2023-03-01: s3://myorg/disease-vocab.parquet
```

This would also be great for adapting to lamindb. As we'll just auto track the parquet file as a DObject. In that case we could even replace the s3 url to be a DObject id.
