### ISSUE TITLE
Make species first class supported (2/2)

### ISSUE THREAD

**Issue by sunnyosun** [laminlabs/bionty-base#393]
This design doesn't allow different source urls for each species per source version: https://github.com/laminlabs/bionty/issues/343

**Comment by sunnyosun** [comment]
New Design 1:

```
Gene:
  ensembl:
    name: Ensembl
    website: https://www.ensembl.org/index.html
    release-108:
      human:
        source: https://ftp.ensembl.org/pub/release-108/mysql/human
        md5: ""
      mouse:
        source: https://ftp.ensembl.org/pub/release-108/mysql/mouse
        md5: ""
    release-107:
      human:
        source: https://ftp.ensembl.org/pub/release-107/mysql/human
        md5: ""
CellType:
  cl:
    name: Cell Ontology
    website: https://obophenotype.github.io/cell-ontology/
    2023-02-15:
      all:
        source: http://purl.obolibrary.org/obo/cl/releases/2023-02-15/cl-base.owl
        md5: 9331a6a029cb1863bd0584ab41508df7
    2022-08-16:
      all:
        source: http://purl.obolibrary.org/obo/cl/releases/2022-08-16/cl.owl
        md5: d0655766574e63f3fe5ed56d3c030880
```

**Comment by sunnyosun** [comment]
New Design 2:
```
Gene:
  ensembl:
    name: Ensembl
    website: https://www.ensembl.org/index.html
    human:
      release-108:
        source: https://ftp.ensembl.org/pub/release-108/mysql/human
        md5: ""
      release-107:
        source: https://ftp.ensembl.org/pub/release-107/mysql/human
        md5: 
    mouse:
      release-108:
        source: https://ftp.ensembl.org/pub/release-108/mysql/mouse
        md5: ""
CellType:
  cl:
    name: Cell Ontology
    website: https://obophenotype.github.io/cell-ontology/
    all:
      2023-02-15:
        source: http://purl.obolibrary.org/obo/cl/releases/2023-02-15/cl-base.owl
        md5: 9331a6a029cb1863bd0584ab41508df7
      2022-08-16:
        source: http://purl.obolibrary.org/obo/cl/releases/2022-08-16/cl.owl
        md5: d0655766574e63f3fe5ed56d3c030880
```
